import type { Review } from "@/types/domain";

/** Fictional reviews for UI only — not verified claims about real people. */
export const reviews: Review[] = [
  {
    id: "r1",
    surgeonId: "s1",
    procedureId: "p-rhino",
    surgeryYear: 2023,
    satisfactionScore: 5,
    communicationScore: 5,
    aftercareScore: 4,
    clinicCleanlinessScore: 5,
    hadComplications: false,
    complicationDetails: null,
    wouldRecommend: true,
    recoveryNotes:
      "Swelling lasted longer than brochure suggested; team answered messages within a day.",
    comment:
      "Consult was detailed; consent form had risks in plain language. No outcome guarantees discussed—which I appreciated.",
    authorDisplay: "ResearchPatient_47",
  },
  {
    id: "r2",
    surgeonId: "s1",
    procedureId: "p-rhino",
    surgeryYear: 2022,
    satisfactionScore: 4,
    communicationScore: 4,
    aftercareScore: 3,
    clinicCleanlinessScore: 5,
    hadComplications: true,
    complicationDetails: "Minor asymmetry noted at 6 weeks; observation plan discussed.",
    wouldRecommend: true,
    recoveryNotes: "Follow-up cadence was clear; revision talk was not rushed.",
    comment:
      "Felt like a research discussion, not a sales pitch. Wish after-hours line was clearer.",
    authorDisplay: "TB_Reviewer",
  },
  {
    id: "r3",
    surgeonId: "s6",
    procedureId: "p-rhino",
    surgeryYear: 2024,
    satisfactionScore: 4,
    communicationScore: 5,
    aftercareScore: 4,
    clinicCleanlinessScore: 4,
    hadComplications: false,
    complicationDetails: null,
    wouldRecommend: true,
    recoveryNotes: "Activity limits were repeated at every visit—good for memory.",
    comment:
      "Price breakdown could be clearer earlier, but overall transparency on risks was strong.",
    authorDisplay: "Anon_Rhino_019",
  },
  {
    id: "r4",
    surgeonId: "s3",
    procedureId: "p-ba",
    surgeryYear: 2023,
    satisfactionScore: 5,
    communicationScore: 5,
    aftercareScore: 5,
    clinicCleanlinessScore: 5,
    hadComplications: false,
    complicationDetails: null,
    wouldRecommend: true,
    recoveryNotes: "Posted recovery checklist matched my experience closely.",
    comment: "Structured fields in the portal matched what the surgeon said in person.",
    authorDisplay: "BatumiTraveler",
  },
  {
    id: "r5",
    surgeonId: "s4",
    procedureId: "p-lipo",
    surgeryYear: 2023,
    satisfactionScore: 3,
    communicationScore: 3,
    aftercareScore: 2,
    clinicCleanlinessScore: 4,
    hadComplications: false,
    complicationDetails: null,
    wouldRecommend: false,
    recoveryNotes:
      "Contour improved but support response slowed after week two—your mileage may vary.",
    comment:
      "Posting for transparency: not malpractice claims—just logistic friction.",
    authorDisplay: "CoastalUser22",
  },
  {
    id: "r6",
    surgeonId: "s8",
    procedureId: "p-abdo",
    surgeryYear: 2022,
    satisfactionScore: 5,
    communicationScore: 5,
    aftercareScore: 5,
    clinicCleanlinessScore: 5,
    hadComplications: false,
    complicationDetails: null,
    wouldRecommend: true,
    recoveryNotes: "DVT prevention explained with written sheet; ER criteria highlighted.",
    comment: "Felt medically responsible tone throughout.",
    authorDisplay: "RecoveryLogger",
  },
  {
    id: "r7",
    surgeonId: "s11",
    procedureId: "p-revision",
    surgeryYear: 2024,
    satisfactionScore: 4,
    communicationScore: 5,
    aftercareScore: 4,
    clinicCleanlinessScore: 5,
    hadComplications: false,
    complicationDetails: null,
    wouldRecommend: true,
    recoveryNotes: "Revision expectations framed as ranges, not promises.",
    comment:
      "Useful compare-and-contrast with imaging from prior surgeon (with my permission).",
    authorDisplay: "RevisionRead_88",
  },
  {
    id: "r8",
    surgeonId: "s5",
    procedureId: "p-bleph",
    surgeryYear: 2023,
    satisfactionScore: 5,
    communicationScore: 4,
    aftercareScore: 5,
    clinicCleanlinessScore: 5,
    hadComplications: false,
    complicationDetails: null,
    wouldRecommend: true,
    recoveryNotes: "Dry eye checklist was helpful pre-op.",
    comment: "Appreciated neutral language—no fear-based marketing.",
    authorDisplay: "LidLiftCurious",
  },
];

export function getReviewsForSurgeon(surgeonId: string): Review[] {
  return reviews.filter((r) => r.surgeonId === surgeonId);
}
