import type { Surgeon } from "@/types/domain";

const edu = (s: string[]) => s;
const certs = (s: string[]) => s;
const rf = (s: string[]) => s;

export const surgeons: Surgeon[] = [
  {
    id: "s1",
    name: "Dr. Nino Kvernadze, MD",
    specialty: "Rhinoplasty & revision rhinoplasty",
    city: "Tbilisi",
    clinic: "Akhaldaba Aesthetic Institute",
    experienceYears: 14,
    procedures: ["rhinoplasty", "revision-surgery", "blepharoplasty"],
    consultationPrice: 180,
    instagram: "@nino_k_rhino",
    website: "https://example.org/ninok",
    verified: true,
    education: edu([
      "Tbilisi State Medical University, MD",
      "Rhinoplasty fellowship (EU)",
    ]),
    certifications: certs([
      "Board-eligible facial plastic surgery (fictional credential)",
    ]),
    bio: "Focus on primary and revision nasal surgery with conservative, function-first planning.",
    beforeAfterAvailable: true,
    reviewSummary:
      "Patients frequently cite clear consent discussions; mixed notes on wait times for revisions.",
    redFlags: [
      "Several reviews mention pressure to book within 48 hours (anecdotal, unverified)",
    ],
    sourceLinks: [{ label: "Public CV summary", url: "#" }],
    patientRating: 4.5,
    image: null,
  },
  {
    id: "s2",
    name: "Dr. Giorgi Malania, MD",
    specialty: "Facial plastic surgery",
    city: "Tbilisi",
    clinic: "Vake Surgical Suites",
    experienceYears: 11,
    procedures: ["facelift", "blepharoplasty", "rhinoplasty"],
    consultationPrice: 160,
    instagram: null,
    website: null,
    verified: true,
    education: edu(["TSMU MD", "ENT-focused residency (fictional)"]),
    certifications: certs(["Facial aesthetic surgery certificate (fictional)"]),
    bio: "Balanced approach to midface and periorbital surgery; emphasizes recovery planning.",
    beforeAfterAvailable: true,
    reviewSummary:
      "Communication scores trend high; aftercare responsiveness varies in older reviews.",
    redFlags: [],
    sourceLinks: [],
    patientRating: 4.3,
    image: null,
  },
  {
    id: "s3",
    name: "Dr. Ana Lomidze, MD",
    specialty: "Breast & body contouring",
    city: "Tbilisi",
    clinic: "Riverbank Plastic Surgery Center",
    experienceYears: 9,
    procedures: ["breast-augmentation", "breast-reduction", "abdominoplasty", "liposuction"],
    consultationPrice: 200,
    instagram: "@ana_lom_plastic",
    website: "https://example.org/analom",
    verified: true,
    education: edu(["TSMU MD", "Plastic surgery residency (fictional)"]),
    certifications: certs(["Breast surgery symposium faculty (fictional)"]),
    bio: "Body contouring with staged recovery education; emphasizes risk counseling.",
    beforeAfterAvailable: true,
    reviewSummary:
      "Strong aftercare documentation in structured reviews; complex cases referred out transparently.",
    redFlags: [],
    sourceLinks: [{ label: "Clinic transparency page", url: "#" }],
    patientRating: 4.6,
    image: null,
  },
  {
    id: "s4",
    name: "Dr. Levan Beridze, MD",
    specialty: "Liposuction & body sculpting",
    city: "Batumi",
    clinic: "Black Sea Cosmetic Clinic",
    experienceYears: 8,
    procedures: ["liposuction", "abdominoplasty", "gynecomastia"],
    consultationPrice: 140,
    instagram: null,
    website: null,
    verified: false,
    education: edu(["TSMU MD"]),
    certifications: certs([]),
    bio: "High-volume liposuction with emphasis on limits of skin retraction.",
    beforeAfterAvailable: false,
    reviewSummary:
      "Praise for honest expectations; some complaints about post-op contact windows.",
    redFlags: rf([
      "Sparse third-party verification of training claims on public profiles",
    ]),
    sourceLinks: [],
    patientRating: 4.0,
    image: null,
  },
  {
    id: "s5",
    name: "Dr. Mariam Chkheidze, MD",
    specialty: "Oculoplastic surgery",
    city: "Tbilisi",
    clinic: "Liberty Eye & Face Clinic",
    experienceYears: 13,
    procedures: ["blepharoplasty", "otoplasty", "revision-surgery"],
    consultationPrice: 150,
    instagram: "@mchk_eyes",
    website: "https://example.org/mariam",
    verified: true,
    education: edu(["TSMU MD", "Ophthalmology + oculoplastics track (fictional)"]),
    certifications: certs(["Tear film & eyelid position coursework (fictional)"]),
    bio: "Prioritizes dry-eye risk discussion and staged upper/lower lid planning.",
    beforeAfterAvailable: true,
    reviewSummary:
      "High cleanliness scores; communication described as thorough but sometimes brisk.",
    redFlags: [],
    sourceLinks: [],
    patientRating: 4.4,
    image: null,
  },
  {
    id: "s6",
    name: "Dr. David Tsereteli, MD",
    specialty: "Rhinoplasty & facial balance",
    city: "Tbilisi",
    clinic: "Mtatsminda Surgical Arts",
    experienceYears: 16,
    procedures: ["rhinoplasty", "chin-augmentation", "revision-surgery"],
    consultationPrice: 220,
    instagram: null,
    website: "https://example.org/dtsereteli",
    verified: true,
    education: edu(["TSMU MD", "International observerships (fictional)"]),
    certifications: certs(["Rhinoplasty-focused CME (fictional)"]),
    bio: "Profile harmony focus with emphasis on airway documentation.",
    beforeAfterAvailable: true,
    reviewSummary:
      "Longer consults noted positively; price transparency described as uneven across reviewers.",
    redFlags: rf([
      "Two reviews cite unclear revision pricing until late in process (anecdotal)",
    ]),
    sourceLinks: [{ label: "Ethics statement", url: "#" }],
    patientRating: 4.2,
    image: null,
  },
  {
    id: "s7",
    name: "Dr. Ketevan Bolkvadze, MD",
    specialty: "Breast surgery",
    city: "Kutaisi",
    clinic: "Rioni Medical Plaza",
    experienceYears: 10,
    procedures: ["breast-augmentation", "breast-reduction", "gynecomastia"],
    consultationPrice: 130,
    instagram: "@ket_plastic",
    website: null,
    verified: false,
    education: edu(["TSMU MD"]),
    certifications: certs([]),
    bio: "Regional breast surgery focus with emphasis on pre-op sizing education.",
    beforeAfterAvailable: true,
    reviewSummary:
      "Patients note friendly staff; a subset want more complication statistics in writing.",
    redFlags: [],
    sourceLinks: [],
    patientRating: 4.1,
    image: null,
  },
  {
    id: "s8",
    name: "Dr. Zurab Papitashvili, MD",
    specialty: "Abdominoplasty & massive weight loss body contouring",
    city: "Tbilisi",
    clinic: "Eastside Body Contouring",
    experienceYears: 12,
    procedures: ["abdominoplasty", "liposuction", "revision-surgery"],
    consultationPrice: 190,
    instagram: null,
    website: "https://example.org/zpapi",
    verified: true,
    education: edu(["TSMU MD", "Body contouring fellowship (fictional)"]),
    certifications: certs(["DVT prevention protocols training (fictional)"]),
    bio: "Staged safety focus for higher-BMI candidates where appropriate.",
    beforeAfterAvailable: true,
    reviewSummary:
      "Strong on recovery realism; several reviews mention long clinic wait times.",
    redFlags: [],
    sourceLinks: [],
    patientRating: 4.35,
    image: null,
  },
  {
    id: "s9",
    name: "Dr. Elene Gvasalia, MD",
    specialty: "Minimally invasive facial rejuvenation (surgical)",
    city: "Tbilisi",
    clinic: "Sololaki Skin & Surgery Lab",
    experienceYears: 7,
    procedures: ["facelift", "blepharoplasty", "buccal-fat-removal"],
    consultationPrice: 170,
    instagram: "@elene_gv",
    website: null,
    verified: true,
    education: edu(["TSMU MD"]),
    certifications: certs(["Facelift technique workshop (fictional)"]),
    bio: "Discusses long-term midface volume tradeoffs for buccal fat decisions.",
    beforeAfterAvailable: false,
    reviewSummary:
      "Younger patient base; appreciation for conservative planning and journaling prompts.",
    redFlags: [],
    sourceLinks: [],
    patientRating: 4.5,
    image: null,
  },
  {
    id: "s10",
    name: "Dr. Irakli Shengelia, MD",
    specialty: "Gynecomastia & chest wall contour",
    city: "Batumi",
    clinic: "Batumi Surgical Collaborative",
    experienceYears: 6,
    procedures: ["gynecomastia", "liposuction"],
    consultationPrice: 120,
    instagram: null,
    website: null,
    verified: false,
    education: edu(["TSMU MD"]),
    certifications: certs([]),
    bio: "Encourages endocrine workup when indicated before surgery.",
    beforeAfterAvailable: true,
    reviewSummary:
      "Smaller review sample; early trends show clear complication disclosure language.",
    redFlags: rf([
      "Limited public outcomes data for gynecomastia subset",
    ]),
    sourceLinks: [],
    patientRating: 3.9,
    image: null,
  },
  {
    id: "s11",
    name: "Dr. Salome Janelidze, MD",
    specialty: "Revision rhinoplasty",
    city: "Tbilisi",
    clinic: "Saburtalo Precision Rhinoplasty",
    experienceYears: 15,
    procedures: ["revision-surgery", "rhinoplasty", "chin-augmentation"],
    consultationPrice: 250,
    instagram: "@salome_r1",
    website: "https://example.org/salomej",
    verified: true,
    education: edu(["TSMU MD", "Craniofacial interest track (fictional)"]),
    certifications: certs(["Revision rhinoplasty symposium lead (fictional)"]),
    bio: "Selective intake for complex revision; emphasizes imaging discussion when useful.",
    beforeAfterAvailable: true,
    reviewSummary:
      "Patients credit blunt talk about limits; fewer same-year surgery slots noted.",
    redFlags: [],
    sourceLinks: [],
    patientRating: 4.55,
    image: null,
  },
  {
    id: "s12",
    name: "Dr. Tamar Gogeshvili, MD",
    specialty: "Otoplasty & pediatric otoplasty consults",
    city: "Kutaisi",
    clinic: "Greenhill ENT & Aesthetics",
    experienceYears: 9,
    procedures: ["otoplasty", "rhinoplasty"],
    consultationPrice: 110,
    instagram: null,
    website: null,
    verified: true,
    education: edu(["TSMU MD", "Pediatric surgery exposure (fictional)"]),
    certifications: certs(["Ear reconstruction coursework (fictional)"]),
    bio: "Emphasizes cartilage timing and realistic symmetry goals for otoplasty.",
    beforeAfterAvailable: true,
    reviewSummary:
      "Families note calm communication; adult otoplasty volume lower than pediatric consults.",
    redFlags: [],
    sourceLinks: [],
    patientRating: 4.45,
    image: null,
  },
  {
    id: "s13",
    name: "Dr. Besik Shubladze, MD",
    specialty: "Chin & jawline aesthetics",
    city: "Tbilisi",
    clinic: "Old Town Face Balance",
    experienceYears: 10,
    procedures: ["chin-augmentation", "rhinoplasty", "liposuction"],
    consultationPrice: 165,
    instagram: "@besh_face",
    website: null,
    verified: false,
    education: edu(["TSMU MD"]),
    certifications: certs([]),
    bio: "Profile analysis with dental coordination when occlusion questions arise.",
    beforeAfterAvailable: false,
    reviewSummary:
      "Mixed on consultation length—some want more written summaries after consult.",
    redFlags: rf([
      "One thread mentions perceived upselling of add-on procedures (unverified)",
    ]),
    sourceLinks: [],
    patientRating: 4.0,
    image: null,
  },
  {
    id: "s14",
    name: "Dr. Lika Kashia, MD",
    specialty: "Breast reduction & lift",
    city: "Tbilisi",
    clinic: "Women's Reconstructive & Aesthetic Center",
    experienceYears: 13,
    procedures: ["breast-reduction", "breast-augmentation", "revision-surgery"],
    consultationPrice: 175,
    instagram: null,
    website: "https://example.org/lika",
    verified: true,
    education: edu(["TSMU MD", "Breast oncology-adjacent training (fictional)"]),
    certifications: certs(["Oncoplastic principles lecture series (fictional)"]),
    bio: "Discusses scar patterns and sensation changes with standardized handouts.",
    beforeAfterAvailable: true,
    reviewSummary:
      "High marks for clinic cleanliness; some longer wait for non-urgent follow-ups.",
    redFlags: [],
    sourceLinks: [],
    patientRating: 4.48,
    image: null,
  },
  {
    id: "s15",
    name: "Dr. Mikheil Abramishvili, MD",
    specialty: "General plastic surgery (mixed caseload)",
    city: "Batumi",
    clinic: "Harbor View Clinic",
    experienceYears: 5,
    procedures: ["liposuction", "blepharoplasty", "rhinoplasty", "breast-augmentation"],
    consultationPrice: 135,
    instagram: "@misha_plast",
    website: null,
    verified: false,
    education: edu(["TSMU MD"]),
    certifications: certs([]),
    bio: "Broad practice with emphasis on referring complex cases when appropriate.",
    beforeAfterAvailable: false,
    reviewSummary:
      "Early-career profile; reviews still accumulating—interpret with small-sample caution.",
    redFlags: rf([
      "Verify hospital privileges and complication routing for higher-risk procedures",
    ]),
    sourceLinks: [],
    patientRating: 3.85,
    image: null,
  },
];

export function getSurgeonById(id: string): Surgeon | undefined {
  return surgeons.find((s) => s.id === id);
}
